//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_EM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leistung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Leistung()
        {
            this.Tendenz = "NULL";
        }
    
        public int Id { get; set; }
        public System.DateTime Erhebungsdatum { get; set; }
        public int Notenstufe { get; set; }
        public string Tendenz { get; set; }
        public int IdFachLehrer { get; set; }
        public int IdSchülerKlasse { get; set; }
        public System.DateTime LetzteÄnderung { get; set; }
        public int IdArt { get; set; }
    
        public virtual UFachLehrer UFachLehrer { get; set; }
        public virtual SchuelerKlasse SchuelerKlasse { get; set; }
        public virtual Leistungsart Leistungsart { get; set; }
    }
}
