//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_EM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leistungsgruppe
    {
        public int Id { get; set; }
        public string Bez { get; set; }
        public string Gewicht { get; set; }
        public int IdLeistungsart { get; set; }
    
        public virtual Leistungsart Leistungsart { get; set; }
    }
}
