//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_EM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unterrichtsfach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unterrichtsfach()
        {
            this.UFachLehrer = new HashSet<UFachLehrer>();
        }
    
        public int Id { get; set; }
        public string Bez { get; set; }
        public int Stunden { get; set; }
        public int Pos { get; set; }
        public int IdZeugnisfach { get; set; }
    
        public virtual Zeugnisfach Zeugnisfach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UFachLehrer> UFachLehrer { get; set; }
    }
}
