//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
namespace X_EM
=======
namespace X_EM.Model
>>>>>>> ffd4214d6df6defe5bd5aa74435e6e17bd2b3e58
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zeugnisfach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zeugnisfach()
        {
            this.Unterrichtsfach = new HashSet<Unterrichtsfach>();
        }
    
        public int Id { get; set; }
        public string Bez { get; set; }
        public int Pos { get; set; }
        public bool AbschliessendesFach { get; set; }
        public string Fachart { get; set; }
        public bool Vorrueckungsfach { get; set; }
        public int IdKlasse { get; set; }
    
        public virtual Klasse Klasse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unterrichtsfach> Unterrichtsfach { get; set; }
    }
}
