//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_EM.Model
{
   using System;
   using System.Collections.Generic;

   public class Lehrer
   {
      public Lehrer()
      {
      }

      public int Id { get; set; }
      public string Kürzel { get; set; }
      public string Nachname { get; set; }
      public string Vorname { get; set; }
      public string Dienstbezeichnung { get; set; } = null;

      public List<UFachLehrer> UFachLehrer { get; set; } = new List<UFachLehrer>();
      public List<Klasse> Klassenleiter { get; set; } = new List<Klasse>();
      public List<Klasse> StellvertretenderKlassenleiter { get; set; } = new List<Klasse>();
   }
}
