//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_EM.Model
{
   using System;
   using System.Collections.Generic;

   public class SchuelerKlasse
   {
      public SchuelerKlasse()
      {
      }

      public int Id { get; set; }
      //public int IdSchueler { get; set; }
      //public int IdKlasse { get; set; }

      public Schueler Schueler { get; set; }
      public Klasse Klasse { get; set; }
      public List<Leistung> Leistung { get; set; } = new List<Model.Leistung>();
   }
}
