//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_EM.Model
{
   using System;
   using System.Collections.Generic;

   public class Schueler
   {
      public Schueler()
      {
      }

      public int Id { get; set; }
      public string Nachname { get; set; }
      public string Vorname { get; set; }
      public DateTime Geburtsdatum { get; set; }
      public string Geschlecht { get; set; }
      public string Konfession { get; set; }

      public List<SchuelerKlasse> SchuelerKlasse { get; set; } = new List<Model.SchuelerKlasse>();
   }
}
