//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_EM.Model
{
   using System;
   using System.Collections.Generic;

   public class UFachLehrer
   {
      public UFachLehrer()
      {
      }

      public int Id { get; set; }
      public int Stunden { get; set; }
      public DateTime EDatum { get; set; } = DateTime.MinValue;
      public DateTime ADatum { get; set; } = DateTime.MinValue;

      //public int IdUnterrichtsfach { get; set; }
      //public int IdLehrer { get; set; }

      public Unterrichtsfach Unterrichtsfach { get; set; }
      public Lehrer Lehrer { get; set; }

      public List<Leistung> Leistung { get; set; } = new List<Model.Leistung>();
   }
}
