//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_EM.Model
{
    using System;
    using System.Collections.Generic;
    
    public class Zeugnisfach
    {
        public Zeugnisfach()
        {
        }
    
        public int Id { get; set; }
        public string Bez { get; set; }
        public int Pos { get; set; }
        public bool AbschliessendesFach { get; set; }
        public string Fachart { get; set; }
        public bool Vorrueckungsfach { get; set; }
        //public int IdKlasse { get; set; }
    
        public Klasse Klasse { get; set; }

      public List<Unterrichtsfach> Unterrichtsfach { get; set; } = new List<Model.Unterrichtsfach>();
    }
}
