//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOMACreator.Model
{
   using MySql.Data.Entity;
   using System;
   using System.Data.Entity;
   using System.Data.Entity.Infrastructure;

   [DbConfigurationType(typeof(MySqlEFConfiguration))]
   public partial class ModelContext : DbContext
    {
        public ModelContext()
            : base("name=MySQLSchuleNoma4")
        {
        }
    
        public virtual DbSet<Klasse> KlasseSet { get; set; }
        public virtual DbSet<Schule> SchuleSet { get; set; }
        public virtual DbSet<Zeugnisfach> ZeugnisfachSet { get; set; }
        public virtual DbSet<Unterrichtsfach> UnterrichtsfachSet { get; set; }
        public virtual DbSet<Lehrer> LehrerSet { get; set; }
        public virtual DbSet<UFachLehrer> UFachLehrerSet { get; set; }
        public virtual DbSet<SchuelerKlasse> SchuelerKlasseSet { get; set; }
        public virtual DbSet<Schueler> SchuelerSet { get; set; }
        public virtual DbSet<Leistung> LeistungSet { get; set; }
        public virtual DbSet<Leistungsart> LeistungsartSet { get; set; }
        public virtual DbSet<Leistungsgruppe> LeistungsgruppeSet { get; set; }
    }
}
